[build]
  ignore = "/bin/false"
  base = ".massivewikibuilder"
  publish = "output"
  command = "massivewikibuilder/mwb.py -c mwb.yaml -w .. -o output -t this-wiki-themes/alto"

[build.environment]
  PYTHON_VERSION = "3.8"
